-- MySQL Script generated by MySQL Workbench
-- 05/06/16 16:12:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema KMS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KMS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KMS` DEFAULT CHARACTER SET utf8 ;
USE `KMS` ;

-- -----------------------------------------------------
-- Table `KMS`.`tipoUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KMS`.`tipoUsuario` ;

CREATE TABLE IF NOT EXISTS `KMS`.`tipoUsuario` (
  `ID_TIPO_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(20) NOT NULL,
  `DATA_FECHA` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_TIPO_USUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KMS`.`faixa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KMS`.`faixa` ;

CREATE TABLE IF NOT EXISTS `KMS`.`faixa` (
  `ID_FAIXA` INT NOT NULL AUTO_INCREMENT,
  `COR` VARCHAR(20) NOT NULL,
  `SIGNIFICADO` VARCHAR(255) NULL,
  `TEMPO_TREINO` INT NULL,
  `DATA_FECHA` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_FAIXA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KMS`.`cep_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KMS`.`cep_info` ;

CREATE TABLE IF NOT EXISTS `KMS`.`cep_info` (
  `CEP` CHAR(9) NOT NULL COMMENT 'Formato do CEP: XXXXX-XXX',
  `CIDADE` VARCHAR(100) NOT NULL,
  `UF` ENUM('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PR','PB','PA','PE','PI','RJ','RN','RS','RO','RR','SC','SE','SP') NOT NULL,
  PRIMARY KEY (`CEP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KMS`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KMS`.`endereco` ;

CREATE TABLE IF NOT EXISTS `KMS`.`endereco` (
  `ID_ENDERECO` INT NOT NULL AUTO_INCREMENT,
  `TIPO_ENDERECO` VARCHAR(20) NOT NULL COMMENT '--TIPOS DISPONÍVEIS\nResidencial;\nComercial.',
  `CEP` CHAR(9) NOT NULL,
  `LOGRADOURO` VARCHAR(50) NOT NULL,
  `NUMERO` INT NULL,
  `COMPLEMENTO` VARCHAR(100) NULL,
  `BAIRRO` VARCHAR(30) NOT NULL,
  `DATA_FECHA` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_ENDERECO`),
  INDEX `cep_fk_idx` (`CEP` ASC),
  CONSTRAINT `cep_fk`
    FOREIGN KEY (`CEP`)
    REFERENCES `KMS`.`cep_info` (`CEP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KMS`.`telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KMS`.`telefone` ;

CREATE TABLE IF NOT EXISTS `KMS`.`telefone` (
  `ID_TELEFONE` INT NOT NULL AUTO_INCREMENT,
  `TIPO_TELEFONE` VARCHAR(20) NOT NULL COMMENT '--TIPOS DISPONÍVEIS\nResidencial;\nTrabalho;\nCelular;\nFax',
  `NUMERO` VARCHAR(20) NOT NULL,
  `DATA_FECHA` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_TELEFONE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KMS`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KMS`.`usuario` ;

CREATE TABLE IF NOT EXISTS `KMS`.`usuario` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `ID_TIPO_USUARIO` INT NOT NULL,
  `ID_FAIXA` INT NOT NULL,
  `PRIMEIRO_NOME` VARCHAR(30) NOT NULL,
  `SOBRENOME` VARCHAR(30) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `DATA_NASCIMENTO` VARCHAR(10) NOT NULL,
  `SEXO` VARCHAR(1) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `HASH` VARCHAR(100) NOT NULL,
  `ID_TELEFONE` INT NOT NULL,
  `ID_TELEFONE2` INT NULL,
  `ID_ENDERECO` INT NOT NULL,
  `TIPO_SANGUINEO` VARCHAR(5) NULL,
  `DATA_CADASTRO` VARCHAR(10) NOT NULL,
  `DATA_ULTIMO_LOGIN` VARCHAR(20) NULL,
  `DATA_FECHA` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_USUARIO`),
  INDEX `TIPO_USUARIO_FK_idx` (`ID_TIPO_USUARIO` ASC),
  INDEX `FAIXA_USUARIO_FK_idx` (`ID_FAIXA` ASC),
  INDEX `ENDERECO_USUARIO_FK_idx` (`ID_ENDERECO` ASC),
  INDEX `TELEFONE_USUARIO_FK_idx` (`ID_TELEFONE` ASC),
  INDEX `TELEFONE2_USUARIO_FK_idx` (`ID_TELEFONE2` ASC),
  CONSTRAINT `TIPO_USUARIO_FK`
    FOREIGN KEY (`ID_TIPO_USUARIO`)
    REFERENCES `KMS`.`tipoUsuario` (`ID_TIPO_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FAIXA_USUARIO_FK`
    FOREIGN KEY (`ID_FAIXA`)
    REFERENCES `KMS`.`faixa` (`ID_FAIXA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ENDERECO_USUARIO_FK`
    FOREIGN KEY (`ID_ENDERECO`)
    REFERENCES `KMS`.`endereco` (`ID_ENDERECO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TELEFONE_USUARIO_FK`
    FOREIGN KEY (`ID_TELEFONE`)
    REFERENCES `KMS`.`telefone` (`ID_TELEFONE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TELEFONE2_USUARIO_FK`
    FOREIGN KEY (`ID_TELEFONE2`)
    REFERENCES `KMS`.`telefone` (`ID_TELEFONE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KMS`.`associacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KMS`.`associacao` ;

CREATE TABLE IF NOT EXISTS `KMS`.`associacao` (
  `ID_ASSOCIACAO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(50) NOT NULL,
  `DESCRICAO` VARCHAR(255) NULL,
  `ID_TELEFONE` INT NOT NULL,
  `ID_ENDERECO` INT NOT NULL,
  `FUNDADOR` VARCHAR(50) NULL,
  `DATA_FUNDACAO` VARCHAR(10) NULL,
  `LOGO` VARCHAR(255) NULL,
  `DATA_FECHA` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_ASSOCIACAO`),
  INDEX `ENDERECO_ASSOCIACAO_FK_idx` (`ID_ENDERECO` ASC),
  INDEX `TELEFONE_ASSOCIACAO_FK_idx` (`ID_TELEFONE` ASC),
  CONSTRAINT `ENDERECO_ASSOCIACAO_FK`
    FOREIGN KEY (`ID_ENDERECO`)
    REFERENCES `KMS`.`endereco` (`ID_ENDERECO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TELEFONE_ASSOCIACAO_FK`
    FOREIGN KEY (`ID_TELEFONE`)
    REFERENCES `KMS`.`telefone` (`ID_TELEFONE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KMS`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KMS`.`evento` ;

CREATE TABLE IF NOT EXISTS `KMS`.`evento` (
  `ID_EVENTO` INT NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT NOT NULL COMMENT 'Identificação do usuário que criou o evento.',
  `NOME` VARCHAR(50) NOT NULL,
  `DESCRICAO` VARCHAR(500) NULL,
  `ID_ENDERECO` INT NOT NULL,
  `DATA_HORA` VARCHAR(20) NOT NULL,
  `TAXA_INSCRICAO` DOUBLE NOT NULL,
  `DATA_FECHA` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_EVENTO`),
  INDEX `USUARIO_EVENTO_FK_idx` (`ID_USUARIO` ASC),
  INDEX `ENDERECO_EVENTO_FK_idx` (`ID_ENDERECO` ASC),
  CONSTRAINT `USUARIO_EVENTO_FK`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `KMS`.`usuario` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ENDERECO_EVENTO_FK`
    FOREIGN KEY (`ID_ENDERECO`)
    REFERENCES `KMS`.`endereco` (`ID_ENDERECO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KMS`.`pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KMS`.`pagamento` ;

CREATE TABLE IF NOT EXISTS `KMS`.`pagamento` (
  `ID_PAGAMENTO` INT NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT NOT NULL COMMENT 'Identificador do usuário que efetuou o pagamento.',
  `DESCRICAO` VARCHAR(200) NULL,
  `VALOR` DOUBLE NOT NULL,
  `MULTA` DOUBLE NULL,
  `DATA_PAGAMENTO` VARCHAR(10) NOT NULL,
  `DATA_FECHA` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_PAGAMENTO`),
  INDEX `USUARIO_PAGAMENTO_FK_idx` (`ID_USUARIO` ASC),
  CONSTRAINT `USUARIO_PAGAMENTO_FK`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `KMS`.`usuario` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KMS`.`aula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KMS`.`aula` ;

CREATE TABLE IF NOT EXISTS `KMS`.`aula` (
  `ID_AULA` INT NOT NULL AUTO_INCREMENT,
  `DATA_AULA` VARCHAR(10) NOT NULL,
  `CONTEUDO_MINISTRADO` VARCHAR(500) NULL,
  `DATA_FECHA` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_AULA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KMS`.`frequencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KMS`.`frequencia` ;

CREATE TABLE IF NOT EXISTS `KMS`.`frequencia` (
  `ID_ALUNO` INT NOT NULL,
  `ID_AULA` INT NOT NULL,
  `PRESENTE` TINYINT(1) NULL,
  PRIMARY KEY (`ID_ALUNO`, `ID_AULA`),
  INDEX `id_aula_fk_idx` (`ID_AULA` ASC),
  CONSTRAINT `id_aluno_fk`
    FOREIGN KEY (`ID_ALUNO`)
    REFERENCES `KMS`.`usuario` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_aula_fk`
    FOREIGN KEY (`ID_AULA`)
    REFERENCES `KMS`.`aula` (`ID_AULA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
